Homework 3
IskanderNakipov/Made2019Autumn pull request #1
Opened 2019-11-17 19:36 UTC by IskanderNakipov

2019-12-05 01:55 UTC, ylyubimov requested changes

2019-12-05 01:55 UTC, ylyubimov commented on Seminar3/Homework/task_6/main.cpp
> +  ~Tree();
Правило 5ти

2019-12-05 01:55 UTC, ylyubimov commented on Seminar3/Homework/task_6/main.cpp
> +  delete_subtree(root->left);
Рекурсивные реализации были запрещены

2019-12-05 01:55 UTC, ylyubimov commented on Seminar3/Homework/task_6/main.cpp
> +  delete_subtree(root->left);
а почему просто не вызвать delete_subtree(root)

2019-12-05 01:55 UTC, ylyubimov commented on Seminar3/Homework/task_6/main.cpp
> +    std::cout << node->value << " ";
ввод/вывод только в main'е должен быть

2019-12-05 01:55 UTC, ylyubimov commented on Seminar3/Homework/task_6/main.cpp
> +  TreeNode *parent = nullptr;
parent тебе не нужен, а только мешает

2019-12-05 01:55 UTC, ylyubimov commented on Seminar3/Homework/task_6/main.cpp
> +  void Print();
Не принт, а PreOrder
И чтобы можно было вызвать что-то типа
tree.PreOrder([](int value) { std::cout << value << std::endl; });

2019-12-05 01:55 UTC, ylyubimov commented on Seminar3/Homework/task_6/main.cpp
> +  void Print();
плюс метод должен быть const

2019-12-05 01:55 UTC, ylyubimov commented on Seminar3/Homework/task_6/main.cpp
> +  delete_subtree(root->left);
Удалять можно тоже с помощью преордер обхода, если слегка подумать)

2019-12-07 18:40 UTC, IskanderNakipov commented on Seminar3/Homework/task_6/main.cpp
> +  delete_subtree(root->left);
Да, но delete_subtree не рекурсивная
Когда писал, не смог придумать, как обработать случай, когда мы поднимаемся снизу и натыкаемся на корень. Поэтому решил корень отдельно обрабатывать.
Просто если мы удалим корень при подъеме, то потом не сможем уже пройти в правую половину, т.к. потеряется ссылка.

2019-12-07 18:45 UTC, IskanderNakipov commented on Seminar3/Homework/task_6/main.cpp
> +  TreeNode *parent = nullptr;
Тогда возникает вопрос, как подниматься наверх. У меня была мысль как-то запоминать путь спуска, но подход с родителем мне показался более "древесным" и красивым.

2019-12-07 19:21 UTC, IskanderNakipov commented on Seminar3/Homework/task_6/main.cpp
> +  ~Tree();
- [ ]

2019-12-07 19:25 UTC, IskanderNakipov commented on Seminar3/Homework/task_6/main.cpp
> +    std::cout << node->value << " ";
check*

2019-12-07 19:27 UTC, IskanderNakipov commented on Seminar3/Homework/task_6/main.cpp
> +  void Print();
> Не принт, а PreOrder
> И чтобы можно было вызвать что-то типа
> tree.PreOrder([](int value) { std::cout << value << std::endl; });

Сделал через лямбды
check*

2019-12-07 19:42 UTC, IskanderNakipov commented on Seminar3/Homework/task_6/main.cpp
> +  void Print();
Только не будет ли проблем, если будет подана не const лямбда? Не получается прогуглить такое

2019-12-07 19:57 UTC, IskanderNakipov commented on Seminar3/Homework/task_6/main.cpp
> +  delete_subtree(root->left);
Если в рамках подхода, когда мы составляем список порядка обхода, то да. Но если мы лишь локально смотрим на данные (то бишь, получаем информацию о дальнейших шагах из ноды, на которой стоим), то удалить ноду, стоя на ней, как мне кажется,невозможно.

2019-12-10 04:46 UTC, ylyubimov commented on Seminar3/Homework/task_6/main.cpp
> +  void Print();
Если ее передал клиент, то это его ответственность

2019-12-10 04:47 UTC, ylyubimov commented on Seminar3/Homework/task_6/main.cpp
> +  TreeNode *parent = nullptr;
stack. Тогда подъемов на верх не будет.

2019-12-10 04:49 UTC, ylyubimov commented on Seminar3/Homework/task_6/main.cpp
> +  actor(root);
а если дерево пустое?

2019-12-10 04:49 UTC, ylyubimov commented on Seminar3/Homework/task_6/main.cpp
> +  delete_subtree(root->left);
Т.к. у тебя не через стек реализовано, то да тебе сложно.

2019-12-10 04:49 UTC, ylyubimov approved these changes

2019-12-14 12:18 UTC, merged